### PR TITLE
LikeAddEvent

### PR DESCRIPTION
**Pull request by bertek41**

### CODE REVIEW

**Comment by BONNe** [comment]
I do not understand why you need an extra event, if one, with exactly the same parameters, is called above.

**Comment by bertek41** [comment]
> I do not understand why you need an extra event, if one, with exactly the same parameters, is called above.

Because i can't listen that event it throws error.

**Comment by BONNe** [comment]
Well, you can listen to events only in the BentoBox environment. 
From outside you need to listen for "BentoBoxEvent" and check if the name is "LikesAddEvent".

**Comment by bertek41** [comment]
Yes but still you can't get much details from BentoBoxEvent. Or is there field to keyValues converter?

**Comment by BONNe** [comment]
It has...
https://github.com/BentoBoxWorld/BentoBox/blob/42622d6e3855e81f3a2174d6aed8c56b96caba8e/src/main/java/world/bentobox/bentobox/api/events/BentoBoxEvent.java#L54

**Comment by bertek41** [comment]
Okay then mb we can close this pr.

**Pull request closed without merging**
